### ISSUE TITLE
How to save the model generated by fitting

### ISSUE THREAD

**Issue by yishengsjh** [Anselmoo/RBF_NetworkFitting#17]
Hello，Thank you for the project，Now I have a  problem that how do I save the model generated by fitting to avoid re fitting each time I load it. Thanks！

**Comment by Anselmoo** [comment]
Thx @yishengsjh  for asking me. 

In terms of using it via `command line`. It should save:

https://github.com/Anselmoo/RBF_NetworkFitting/blob/db8742934b73b8172be16c277919f210aa8a08df/RBFN/__main__.py#L69

In terms of using as a module:

https://github.com/Anselmoo/RBF_NetworkFitting/blob/db8742934b73b8172be16c277919f210aa8a08df/RBFN/RBFNetwork.py#L208-L272

__values__ are returned and can be saved via `np.savetxt` for example.

I hope that helps.

**Comment by yishengsjh** [comment]
> Thx @yishengsjh for asking me.
> 
> In terms of using it via `command line`. It should save:
> 
> https://github.com/Anselmoo/RBF_NetworkFitting/blob/db8742934b73b8172be16c277919f210aa8a08df/RBFN/__main__.py#L69
> 
> In terms of using as a module:
> 
> https://github.com/Anselmoo/RBF_NetworkFitting/blob/db8742934b73b8172be16c277919f210aa8a08df/RBFN/RBFNetwork.py#L208-L272
> 
> **values** are returned and can be saved via `np.savetxt` for example.
> 
> I hope that helps.
Thank you very much for your answer. But I think you may have misunderstood what I mean. 
For example, I used a set of training data to generate an RBF-Network. Now, I'm going to save this model so that next time I enter it directly into this network, I can get the data that this network fits.
 I'm a novice, don't know if you can understand this statement?

**Comment by yishengsjh** [comment]
Thank you very much for your answer. But I think you may have misunderstood what I mean.
For example, I used a set of training data to generate an RBF-Network. Now, I'm going to save this model so that next time I enter it directly into this network, I can get the data that this network fits.
I'm a novice, don't know if you can understand this statement?

**Comment by yishengsjh** [comment]
https://github.com/Anselmoo/RBF_NetworkFitting/blob/db8742934b73b8172be16c277919f210aa8a08df/RBFN/RBFNetwork.py#L275-L298

After line 291 I want to add below code to Generate a new set of data to verify the generated network.
  ```
# Generate a new set of data to validate the generated network

        x_p = np.linspace(-20, 20, 100)

        y_p = np.sin(x) + np.cos(x) ** 2 + np.random.uniform(-0.1, 0.1,
                                                             100) + x ** 3

       y_prediction = model.predict(x_p);

        plt.plot(x_p, y_p, 'b-', label='real')

        `plt.plot(x_p, y_prediction, 'r-', label='fit')`
```
But the final effect seems a bit absurd. I don't know if my verification is correct. Could you give me some suggestions？
![d08434c3a1ceaf8f4055093054a91bd](https://user-images.githubusercontent.com/81353635/202097642-30cfc444-cc7c-4330-9d6a-80a63ecbf15b.png)

**Comment by Anselmoo** [comment]
@yishengsjh thx for explaining to me again.

My proposed network was developed for some _academic_ challenges and since not been touched anymore.

If you are looking for an established routine, please take a look here https://github.com/topics/radial-basis-function-network

**Comment by Anselmoo** [comment]
@yishengsjh  one more thing, do have you played with the number of hidden layers?

https://github.com/Anselmoo/RBF_NetworkFitting/blob/db8742934b73b8172be16c277919f210aa8a08df/RBFN/RBFNetwork.py#L8

If you only the number of layers is too small in reference to the complex `cos sin` function, it might be under fitted.

**Comment by yishengsjh** [comment]
> one more thing, do have you played with the number of hidden layers?


Thank you for reminding me of this，I have only used the default hidden layers.I think it's worth a try.
Thanks again for your help！

**Comment by Anselmoo** [comment]
You should definitely play with the number of layers like https://en.wikipedia.org/wiki/Hyperparameter_optimization
